### ISSUE TITLE
What about esp-open-sdk for ESP8266_RTOS_SDK

### ISSUE THREAD

**Issue by profra** [pfalcon/esp-open-sdk#105]
It would be nice to have so handy tool as esp-open-sdk also for ESP8266_RTOS_SDK. Would you be willing to write so handy integration script for this? ... or to provide advice how to create suitable environment for it?

**Comment by pfalcon** [comment]
See https://github.com/SuperHouse/esp-open-rtos

**Comment by profra** [comment]
Thank you very much, this is it.
