### ISSUE TITLE
Cannot build when LD_LIBRARY_PATH is set

### ISSUE THREAD

**Issue by Phyks** [pfalcon/esp-open-sdk#106]
It is common to set `LD_LIBRARY_PATH`, however build errors if it is set. Why not backupping it, resetting it and restoring it after the build?

Thanks

**Comment by pfalcon** [comment]
It's not common to set it. If you set it, dealing with it is your problem.

**Comment by Phyks** [comment]
Well, it is common if you use some tools, e.g. Torch. Dealing with it is not much overhead on esp-open-sdk side and I think it could be worth it.

**Comment by pfalcon** [comment]
Torch? What Torch? Let them know that they do it wrong. In the meantime, build on clean, Torch-less system, only then mix in that Torch, if you have to.

> Dealing with it is not much overhead on esp-open-sdk side and I think it could be worth it.

Next report: "esp-open-sdk requires computer to build. Why not make it build without computer? It should be easy."

**Comment by Phyks** [comment]
Link added in previous comment, it is a Lua library.

Anyway, guess you made your mind and it is useless to discuss it further.
