### ISSUE TITLE
Does it make sense to build CRT with -ffunction-sections and -fdata-sections?

### ISSUE THREAD

**Issue by Sermus** [pfalcon/esp-open-sdk#113]
Does it make sense to build CRT with function-scoped sections to let linker get rid of unused staff?

**Comment by pfalcon** [comment]
I don't know, try it and report your results.

**Comment by Sermus** [comment]
Can you please give me a hint where i can put additional gcc flags to
compile libs with?

2015-12-08 14:52 GMT+03:00 Paul Sokolovsky <notifications@github.com>:

**Comment by Sermus** [comment]
Does defining CT_TARGET_FLAGS in crosstool-config-overrides do the trick?

**Comment by Sermus** [comment]
This doesn't seem to help. Compiled libs are still compiled in solid-section manner.
