### ISSUE TITLE
Includes not found

### ISSUE THREAD

**Issue by SaimenSays** [pfalcon/esp-open-sdk#121]
Is there a bug in common.mk?
I'm unable to compile because nearly all include directory is not referd. Whatever example I try to compile, there is always the message:
```
   espressif/esp_common.h: No such file or directory
    #include "espressif/esp_common.h"
```
But header file is in correct directory in respect to git checkout root directory. If I change $ROOT in common.mk to have correct include directory, the error changes. Because now compiler is unable to find specific mk files anymore. Maybe some issue with version of make?

Please help!

**Comment by pfalcon** [comment]
You apparently mixed up projects. There's no common.mk in this project. Report bugs to project which owns it.
