### ISSUE TITLE
(THISDIR) use case in Building tool chain section.

### ISSUE THREAD

**Issue by Rishi99es** [pfalcon/esp-open-sdk#149]
$ xtensa-lx106-elf-gcc -I$(THISDIR)/sdk/include -L$(THISDIR)/sdk/lib

I replaced (THISDIR) with a custom directory of my choice.
Both the sections contain same directory as below.

$ xtensa-lx106-elf-gcc -I$**/home/rishi/Documents/esptool/pfalcon**/sdk/include -L$**/home/rishi/Documents/esptool/pfalcon**/sdk/lib

**Errors**:
(directory): cannot find crt1-sim.o: No such file or directory
(directory): cannot find _vectors.o: No such file or directory
(directory): cannot find -lsim
(directory): cannot find -lhandlers-sim
collect2: error: ld returned 1 exit status

**Comment by pfalcon** [comment]
THISDIR is not supposed to be overridden.
