### ISSUE TITLE
REQ: failover mpfr.org to mirror in build scripts

### ISSUE THREAD

**Issue by madeinoz67** [pfalcon/esp-open-sdk#162]
There appears to be reliability issues with www.mpfr.org and so far today Its been down after trying to do a new install. 

After doing a bit of googling it would seem that this is a fairly common thing,  also other OS projects that use www.mpfr.org also have ongoing intermittent reliability issues from the results of posts Ive read in their forums etc .

Is it possibly to include in the build scripts the ability to failover to a mirror site to get necessary toolchain components if the connection fail?

**Comment by pfalcon** [comment]
See https://github.com/pfalcon/esp-open-sdk/issues/100 . Also, https://github.com/pfalcon/esp-open-sdk/pull/146 may or may not alleviate this problem. Feel free to test and report.
