### ISSUE TITLE
Compile newbie: make STANDALONE=n 

### ISSUE THREAD

**Issue by matthewmellor** [pfalcon/esp-open-sdk#174]
Hi I'm new to using ubuntu and new to compiling stuff. I'm trying to compile using the **STANDALONE=n** method and am unsure how to go about the steps. Specifically these are the commands I've entered (in order) within a directory I called esp8266 

`sudo apt-get install make unrar autoconf automake libtool gcc g++ gperf \
    flex bison texinfo gawk ncurses-dev libexpat-dev python python-serial sed \
    git unzip bash help2man`
`sudo apt-get install libtool-bin` 
`git clone --recursive https://github.com/pfalcon/esp-open-sdk.git`
`make STANDALONE=n`

This is working/compiling but I'm unclear about the information under **Using the toolchain**
which says:
  "If you chose the non-standalone SDK, run the compiler with the corresponding include and lib dir flags"

Then the following command is given:

`xtensa-lx106-elf-gcc -I$(THISDIR)/sdk/include -L$(THISDIR)/sdk/lib`

So for a complete newbie like me.... Should this command be combined with the `make STANDALONE=n` command or does it come afterwards? How do I do this? Thanks guys :)

**Comment by bad-mood** [comment]
It comes afterwards. After you clone it, just type in "make STANDALONE=n" (minus the quotes). After this, use the given command to compile using the cross compiler with the files in sdk/include and sdk/lib.
Also read about environment variables in Ubuntu and cross compilers. Kindly close this thread. This does not merit as an issue.
