### ISSUE TITLE
Important SDK Patch Released

### ISSUE THREAD

**Issue by fvpalha** [pfalcon/esp-open-sdk#183]
Hi @pfalcon 

Do you have a schedule to add the [Important SDK Patch Released](http://bbs.espressif.com/viewtopic.php?f=46&t=2407)?

Thank you.

**Comment by fvpalha** [comment]
Hi @pfalcon 

Now they launched [ESP8266_NONOS_SDK_V2.0.0_16_07_19](http://bbs.espressif.com/viewtopic.php?f=46&t=2451).

Thank you.

**Comment by jeremyd2019** [comment]
I made patches for the patch for 1.5.4, and to add the sdk 2.0.0.

I have not tested compiling anything with either yet, but hopefully having a patch/pull request out there will get more eyes on it than just mine.

**Comment by fvpalha** [comment]
Thank you @jeremyd2019

**Comment by stevemk14ebr** [comment]
Attempt to build toolchain with SDK 2.0.0

> 2016-08-09 21:36:41 (6.30 KB/s) - ‘ESP8266_NONOS_SDK_V2.0.0_16_07_19.zip’ saved [5122726/5122726]
> 
> unzip -q -o ESP8266_NONOS_SDK_V2.0.0_16_07_19.zip
> mv ESP8266_NONOS_SDK ESP8266_NONOS_SDK_V2.0.0_16_07_19
> mv License ESP8266_NONOS_SDK_V2.0.0_16_07_19
> mv: cannot stat ‘License’: No such file or directory
> make: [ESP8266_NONOS_SDK_V2.0.0_16_07_19/.dir] Error 1 (ignored)
> touch ESP8266_NONOS_SDK_V2.0.0_16_07_19/.dir
> ln -snf ESP8266_NONOS_SDK_V2.0.0_16_07_19 sdk
> /home/steve/ESPSDK2.0/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -O2 -c user_rf_cal_sector_set.c
> user_rf_cal_sector_set.c:1:21: fatal error: c_types.h: No such file or directory
>  #include <c_types.h>
>                      ^
> compilation terminated.
> make: *** [user_rf_cal_sector_set.o] Error 1
> steve@steve-VirtualBox:~/ESPSDK2.0/esp-open-sdk$ 
> 

Solutions?

**Comment by jeremyd2019** [comment]
@stevemk14ebr - see PR #187

**Comment by stevemk14ebr** [comment]
I'm attempting those modifications now. FYI they released a patch to 2.0.0 today:
http://bbs.espressif.com/viewtopic.php?f=46&t=2529

**Comment by jrobeson** [comment]
Is this still a problem? master uses SDK 2.0 now.

**Comment by pfalcon** [comment]
Closing per above.
