### ISSUE TITLE
STANDALONE=n doesn't make or install lwip-open

### ISSUE THREAD

**Issue by davydnorris** [pfalcon/esp-open-sdk#207]
Selecting STANDALONE=n doesn't make the lwip-open library at all, and it doesn't install lwip header files anywhere, which means the lwip that comes bundled with the sdk doesn't have any header files either.

I would like to suggest that if STANDALONE=n, the lwip-open library gets made and installed under usr/lib with libhal, and the headers get installed somewhere too - perhaps under ${TOP} in a dir named 'extras' (to match CHERTS distribution), or under a dir 'lwip/include' under ${TOP}

**Comment by pfalcon** [comment]
lwip-open isn't supported for STANDALONE=n. STANDALONE=n itself is deprecated and provided as is, mostly for projects which historically use it to build just a toolchain, and don't want to switch to using crosstool-NG directly.
