### ISSUE TITLE
xtensa-lx106 installation

### ISSUE THREAD

**Issue by malgrati-ferdinando** [pfalcon/esp-open-sdk#229]
Hi,
I tried to install ESP8266 sdk and I have the following error.

[e-nand@localhost esp-open-sdk]$ make STANDALONE=y
Makefile:181: warning: overriding commands for target `/.dir'
Makefile:175: warning: ignoring old commands for target `/.dir'
cp esptool/esptool.py /data/Esp8266/esp-open-sdk/xtensa-lx106-elf/bin/
wget --content-disposition "http://bbs.espressif.com/download/file.php?id=1690"
--2016-12-08 16:01:52--  http://bbs.espressif.com/download/file.php?id=1690
Resolving bbs.espressif.com... 119.9.92.91
Connecting to bbs.espressif.com|119.9.92.91|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5177738 (4.9M) [application/octet-stream]
--2016-12-08 16:01:53--  http://bbs.espressif.com/download/file.php?id=1690
Reusing existing connection to bbs.espressif.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 5177738 (4.9M) [application/octet-stream]
Saving to: “file.php?id=1690.1”

100%[===================================================================================================================================================================================================>] 5,177,738    610K/s   in 9.4s    

2016-12-08 16:02:02 (539 KB/s) - “file.php?id=1690.1” saved [5177738/5177738]

unzip -q -o ESP8266_NONOS_SDK_V2.0.0_16_08_10
unzip:  cannot find or open ESP8266_NONOS_SDK_V2.0.0_16_08_10, ESP8266_NONOS_SDK_V2.0.0_16_08_10.zip or ESP8266_NONOS_SDK_V2.0.0_16_08_10.ZIP.
make: *** [/.dir] Error 9

I'm working on linux CentOs 6.x
Linux 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

could you give me an indication to continue?

moreover i want to signal an issue about newlib.tar.xz. this tar file doesn.t work because it is a .gz file, indeed renaming the file the installation is continued, but the issue reported above I'm not able to resolve. 
thanks in advance
Ferdinando

**Comment by pfalcon** [comment]
Your CentOS has very old wget tool. Upgrade to a newer wget version.
