### ISSUE TITLE
esptool submodule update failure

### ISSUE THREAD

**Issue by rith87** [pfalcon/esp-open-sdk#238]
```
$ git submodule update --init
fatal: reference is not a tree: 9dfcb350e1a91bb4641f725fc6c2f126791013ce
Unable to checkout '9dfcb350e1a91bb4641f725fc6c2f126791013ce' in submodule path 'esptool'
```

Looking at the .gitmodules:

```
[submodule "esptool"]
	path = esptool
	url = https://github.com/themadinventor/esptool
```

The submodule redirects to the Espressif repo but I can't seem to get it to work. After switching over to 

```
[submodule "esptool"]
	path = esptool
	url = https://github.com/espressif/esptool
```

The pull seems to work fine. Not sure if this is a configuration issue on my part or not...

**Comment by pfalcon** [comment]
Cannot reproduce, sorry. I assume other folks cannot reproduce either, or there would be more reports of this issue. You may want to clone/submodule-update from scratch.
