### ISSUE TITLE
Failed to build on Ubuntu

### ISSUE THREAD

**Issue by huxq** [pfalcon/esp-open-sdk#242]
Hello,

I recently tried to build the toolchain on a ubuntu16.04 machine and hit a build error.
Looks like it is an access issue to http://www.bastoul.net

[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170218.215140
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_cloog_get[scripts/build/companion_libs/130-cloog.sh@741]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@591]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/crosstool-ng-1.22.0-55-gecfc19a/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 4:42.25)
[04:42] / ct-ng:152: recipe for target 'build' failed
make[2]: *** [build] Error 1
make[2]: Leaving directory '/home/senhai/esp8266/esp-open-sdk/crosstool-NG'
../Makefile:130: recipe for target '_toolchain' failed
make[1]: *** [_toolchain] Error 2
make[1]: Leaving directory '/home/senhai/esp8266/esp-open-sdk/crosstool-NG'
Makefile:126: recipe for target '/home/senhai/esp8266/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc' failed
make: *** [/home/senhai/esp8266/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc] Error 2

When look at the ct-ng build log:
[ALL  ]    --2017-02-18 21:56:11--  (try: 3)  http://www.bastoul.net/cloog/pages/download/cloog-0.18.4
[ALL  ]    Connecting to www.bastoul.net (www.bastoul.net)|62.210.16.62|:80... failed: Connection timed out.
[ALL  ]    Giving up.
[ALL  ]
[DEBUG]    Not at this location: "http://www.bastoul.net/cloog/pages/download/cloog-0.18.4"
[DEBUG]    Trying 'ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.4'
[DEBUG]    ==> Executing: 'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/senhai/esp8266/esp-open-sdk/crosstool-NG/.build/tarballs/cloog-0.18.4.tmp-dl' 'ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.4'
[ALL  ]    --2017-02-18 21:56:22--  ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.4
[ALL  ]               => '/home/senhai/esp8266/esp-open-sdk/crosstool-NG/.build/tarballs/cloog-0.18.4.tmp-dl'
[ALL  ]    Resolving gcc.gnu.org (gcc.gnu.org)... 209.132.180.131
[ALL  ]    Connecting to gcc.gnu.org (gcc.gnu.org)|209.132.180.131|:21... connected.
[ALL  ]    Logging in as anonymous ... Logged in!
[ALL  ]    ==> SYST ... done.    ==> PWD ... done.
[ALL  ]    ==> TYPE I ... done.  ==> CWD (1) /pub/gcc/infrastructure ... done.
[ALL  ]    ==> SIZE cloog-0.18.4 ... done.
[ALL  ]
[ALL  ]    ==> PASV ... done.    ==> RETR cloog-0.18.4 ...
[ALL  ]    No such file 'cloog-0.18.4'.
[ALL  ]
[DEBUG]    Not at this location: "ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.4"
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_cloog_get[scripts/build/companion_libs/130-cloog.sh@741]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@591]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/crosstool-ng-1.22.0-55-gecfc19a/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 4:42.25)
                                                                                                              1233,1        Bot

Looks like the bastoul website is not accessible. When I try from the browser, I can not access the www.bastoul.net URL

From ftp://gcc.gnu.org/pub/gcc/infrastructure/

There is no version 18.4, which seems required by this build

File:cloog-0.16.1.tar.gz
	1725 KB 	2011-01-07 	12:00:00 AM
File:cloog-0.16.2.tar.gz
	1808 KB 	2011-03-23 	12:00:00 AM
File:cloog-0.18.0.tar.gz
	3688 KB 	2012-12-20 	12:00:00 AM
File:cloog-0.18.1.tar.gz
	3767 KB 	2013-10-14 	12:00:00 AM
File:cloog-parma-0.16.1.tar.gz
	1155 KB 	2011-01-07 	12:00:00 AM
File:cloog-ppl-0.15.11.tar.gz
	755 KB 	2011-04-01 	12:00:00 AM
File:

Some of my system information:

$ uname -a
Linux ThinkPad-X200 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by huxq** [comment]
Looks like the proper place to get the GLooG library should be:
http://repo.or.cz/w/cloog.git

According to:
https://gcc.gnu.org/wiki/CLooG

**Comment by pfalcon** [comment]
See #100.
