### ISSUE TITLE
make failing on ubuntu 16.0.4

### ISSUE THREAD

**Issue by kanadenipun** [pfalcon/esp-open-sdk#246]
Error Message (Running on ubuntu 16.0.4):

Makefile:181: warning: overriding recipe for target 'ESP8266_NONOS_SDK_V2.0.0_16_08_10/.dir'
Makefile:176: warning: ignoring old recipe for target 'ESP8266_NONOS_SDK_V2.0.0_16_08_10/.dir'
make -C crosstool-NG -f ../Makefile _ct-ng
make[1]: Entering directory '/home/thoughtworks/esp/esp-open-sdk/crosstool-NG'
../Makefile:181: warning: overriding recipe for target 'ESP8266_NONOS_SDK_V2.0.0_16_08_10/.dir'
../Makefile:176: warning: ignoring old recipe for target 'ESP8266_NONOS_SDK_V2.0.0_16_08_10/.dir'
./bootstrap
Running autoconf...
./bootstrap: 5: ./bootstrap: autoconf: not found
../Makefile:143: recipe for target '_ct-ng' failed
make[1]: *** [_ct-ng] Error 127
make[1]: Leaving directory '/home/thoughtworks/esp/esp-open-sdk/crosstool-NG'
Makefile:140: recipe for target 'crosstool-NG/ct-ng' failed
make: *** [crosstool-NG/ct-ng] Error 2

Using instructions for Ubuntu 14.04 

sudo apt-get install make unrar-free autoconf automake libtool gcc g++ gperf \
    flex bison texinfo gawk ncurses-dev libexpat-dev python-dev python python-serial \
    sed git unzip bash help2man wget bzip2

and then running make however fixed the issue.

**Comment by pfalcon** [comment]
You have ct-ng problems, see #101.
