### ISSUE TITLE
cannot find -ludhcp

### ISSUE THREAD

**Issue by atlask1** [pfalcon/esp-open-sdk#249]
Hi, I have build esp-open-sdk and if I use 'gen_misc.sh' all is ok.
Now I'm tring to write a makefile but when I try to compile return me this error:
`esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: cannot find -ludhcp
collect2: error: ld returned 1 exit status
Makefile:132: set di istruzioni per l'obiettivo "build/app.out" non riuscito
make: *** [build/app.out] Errore 1
`
Surely it's my fault , but could someone make me understand?
thanks

**Comment by atlask1** [comment]
I forgot:
I'm using the last RTOS SDK

**Comment by pfalcon** [comment]
There's no gen_misc.sh in esp-open-sdk.

**Comment by pfalcon** [comment]
See https://github.com/pfalcon/esp-open-sdk/issues/101
