### ISSUE TITLE
Make fails after 861 minutes on cross-gdb "python is missing or unusable"

### ISSUE THREAD

**Issue by stunney** [pfalcon/esp-open-sdk#260]
Hey, trying to compile the toolchain on Raspberry Pi 1B.

**Comment by stunney** [comment]
I got all the way to the Installing cross-gdb step and failed on the fact that I didn't have python2.7-dev installed.  Boooooo.

Can I start up from that step somehow easily?

**Comment by stunney** [comment]
I've commented out the commands in ./Makefile under the clean-sdk, clean, and clean-sysroot steps and ran Make again.  It seems to finish really quickly.  Was I really *THAT* close to the end?

**Comment by stunney** [comment]
And, there should be a pre-check in the build for python-dev :)

**Comment by pfalcon** [comment]
See #101.
