### ISSUE TITLE
Add support for FreeRTOS-based SDK

### ISSUE THREAD

**Issue by Informatic** [pfalcon/esp-open-sdk#28]
The problem is it may need some Makefile rewrite here, since it's not distributed in ZIPs, as far as i know.

https://github.com/espressif/esp_iot_rtos_sdk
https://github.com/espressif/esp_iot_rtos_sdk_lib

**Comment by pfalcon** [comment]
#28 is there as "contributed patches". See also https://github.com/SuperHouse/esp-open-rtos
