### ISSUE TITLE
how to save files in freertos?

### ISSUE THREAD

**Issue by beckmx** [pfalcon/esp-open-sdk#290]
I have been trying to save a file with spiffs but the compiler complains about this error

`error: 'fs' undeclared`

I have these headers

```
#include "esp_common.h"
#include "gpio.h"
#include "queue.h"

#include "spiffs.h"
#include <stdlib.h>
#include "spiffs_test_params.h"

#include "fcntl.h"
#include "unistd.h"
```

Anyone knows how to use spiffs or a better way to create or save data?

**Comment by pfalcon** [comment]
See #101.
