### ISSUE TITLE
error: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by dotlambda** [pfalcon/esp-open-sdk#293]
Quite some time ago, I opened an [issue](https://github.com/jcmvbkbc/crosstool-NG/issues/48) over at corsstool-NG. Sadly, I never got a reply.
Therefore, I thought maybe someone over here can help me out:

> I'm trying to compile crosstool-NG on NixOS (64-bit Linux), but I'm getting the following error during the step "Installing pass-2 core C gcc compiler" (from `build.log`):
> ```
> [ALL  ]    gcc -c -DHAVE_CONFIG_H -O2 -g -pipe -Wno-error=format-security  -I. -I/home/rschuetz/dev/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/libiberty/../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -pedantic  /home/rschuetz/dev/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/libiberty/floatformat.c -o floatformat.o
> [ALL  ]    /home/rschuetz/dev/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/libcpp/expr.c: In function 'unsigned int cpp_classify_number(cpp_reader*, const cpp_token*, const char**, source_location)':
> [ERROR]    /home/rschuetz/dev/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/libcpp/expr.c:629:18: error: format not a string literal and no format arguments [-Werror=format-security]
> [ALL  ]            0, message);
> [ALL  ]                      ^
> [ERROR]    /home/rschuetz/dev/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/libcpp/expr.c:632:39: error: format not a string literal and no format arguments [-Werror=format-security]
> [ALL  ]               virtual_location, 0, message);
> [ALL  ]                                           ^
> ```
> They even do not disappear when I add
> ```
> CT_EXTRA_CFLAGS_FOR_BUILD="-Wno-error=format-security"
> CT_EXTRA_CFLAGS_FOR_HOST="-Wno-error=format-security"
> CT_TARGET_CFLAGS="-Wno-error=format-security"
> ```
> to `.config`.
>
> Do you have an idea how to solve this?

**Comment by dir-ableton** [comment]
@dotlambda I just figured that one out. I can highly recommend using nix for this kind of stuff, as it's literally just a line to swap compilers.

The problem went away after I used a GCC 4.9 to build. Seems rules have tightened in GCC 5 and above. HTH
