### ISSUE TITLE
No rule to make target `esp-open-rtos/lwip/lwip/src/include/lwip/ip_addr.h'

### ISSUE THREAD

**Issue by techboycr** [pfalcon/esp-open-sdk#301]
This is happening to me after install and try to copile my code, I am trying to compile this project: https://github.com/flannelhead/espway

But is giving me this error:  

```
No rule to make target `esp-open-rtos/lwip/lwip/src/include/lwip/ip_addr.h', needed by `build/open_esplibs_libmain//misc.o'
```

Any idea? I am working with the esp-open-sdk directory that they provide.

**Comment by pfalcon** [comment]
> I am working with the esp-open-sdk directory that they provide.

If "they provide", then you ask them. If there's anything related to *this* project, please provide the exact and minimal steps to reproduce (feel free to reopen then).
