### ISSUE TITLE
Bash 5 compilation issue

### ISSUE THREAD

**Issue by Ergus** [pfalcon/esp-open-sdk#356]
Hi bash5 is out in distributions like arch linux, but the regex to check the version in crosstool-NG/configure.ac does not include it. This fixes the issue:

```
diff --git a/configure.ac b/configure.ac
index 5d512fe8..872a73de 100644
--- a/configure.ac
+++ b/configure.ac
@@ -190,7 +190,7 @@ AC_CACHE_VAL([ac_cv_path__BASH],
 AC_CACHE_CHECK([for bash >= 3.1], [ac_cv_path__BASH],
     [AC_PATH_PROGS_FEATURE_CHECK([_BASH], [bash],
         [[_BASH_ver=$($ac_path__BASH --version 2>&1 \
-                     |$EGREP '^GNU bash, version (3\.[1-9]|4)')
+                     |$EGREP '^GNU bash, version (3\.[1-9]|4|5)')
           test -n "$_BASH_ver" && ac_cv_path__BASH=$ac_path__BASH ac_path__BASH_found=:]],                                                           
         [AC_MSG_RESULT([no])
          AC_MSG_ERROR([could not find bash >= 3.1])])])
```

**Comment by pfalcon** [comment]
crosstool-NG/configure.ac is part of crosstool-NG project, not this project.

**Comment by nashley** [comment]
Now that crosstool-NG [has been updated](https://github.com/jcmvbkbc/crosstool-NG/pull/56), can the submodule commit referencing it be updated to pull in the change?

**Comment by rsnyman** [comment]
Yes, please, I was trying to figure out why it wasn't building for me.

**Comment by milkpirate** [comment]
> Now that crosstool-NG [has been updated](https://github.com/jcmvbkbc/crosstool-NG/pull/56), can the submodule commit referencing it be updated to pull in the change?

@pfalcon yes I agree with @nashley, could you please do so?

**Comment by igagis** [comment]
@milkpirate see #387
