### ISSUE TITLE
building toolchain on raspbian

### ISSUE THREAD

**Issue by yizhoucc** [pfalcon/esp-open-sdk#361]
when building toolchain on raspi 3b, i encountered a problem with gcc (seems)

> Build failed in step 'Installing pass-2 core C gcc compiler'

in the log file,
[build.log](https://github.com/pfalcon/esp-open-sdk/files/3114971/build.log)
 it says `[DEBUG]    ==> Executing: '/usr/bin/make' '-j5' '-l' 'all-gcc' 'all-target-libgcc'` `Makefile:3889: recipe for target 'all-gcc' failed` 

the full log is here.

any help is appreciated!!

**Comment by piersfinlayson** [comment]
Looks like you ran out of disk (SD card) space:

`[ALL  ]    /usr/bin/ranlib: libbackend.a: No space left on device`

**Comment by yizhoucc** [comment]
ty, that was dumb.

**Comment by igagis** [comment]
close the issue?
