### ISSUE TITLE
Ubuntu 15.10 requires libtool-bin

### ISSUE THREAD

**Issue by heeen** [pfalcon/esp-open-sdk#58]
checking for GNU libtool >= 1.5.26... no
configure: error: could not find GNU libtool >= 1.5.26

**Comment by thehans** [comment]
I have this same error while attempting to build on Ubuntu 15.04.  

    checking for GNU libtool >= 1.5.26... no
    configure: error: could not find GNU libtool >= 1.5.26
    ../Makefile:238: recipe for target '_ct-ng' failed
    make[1]: *** [_ct-ng] Error 1
    make[1]: Leaving directory '/opt/esp-open-sdk/crosstool-NG'
    Makefile:235: recipe for target 'crosstool-NG/ct-ng' failed
    make: *** [crosstool-NG/ct-ng] Error 2

I have libtool 2.4.2-1.11 installed.

**Comment by pfalcon** [comment]
Addressed in https://github.com/pfalcon/esp-open-sdk/commit/319c54520ca3aeb0b0bdab628a96b3ce51f47eef

**Comment by cebrax** [comment]
Installing libtool-bin solves this issue.

**Comment by mindforger** [comment]
why is the hint from cebrax not added to the readme?
