### ISSUE TITLE
"【News】SDK Memory Optimization - Save 8k SRAM!（SDK 内存优化更新）"

### ISSUE THREAD

**Issue by eriksl** [pfalcon/esp-open-sdk#70]
Can you please incorporate this?

http://bbs.espressif.com/viewtopic.php?f=5&t=743

**Comment by pfalcon** [comment]
Duplicate of #67, #68.

**Comment by eriksl** [comment]
Sorry I didn't see it, must be in need of glasses apparently ;-)

**Comment by pfalcon** [comment]
Nope, just feel free to check already submitted bugs before posting new ;-).

**Comment by eriksl** [comment]
What happened, I think, is that I checked the issues, not the pull requests. It looks to me like the issues already active were actually pull requests. But never mind, I'll check them too in the future.
