### ISSUE TITLE
RTOS SDK

### ISSUE THREAD

**Issue by borg42** [pfalcon/esp-open-sdk#71]
Hi,

Would you be interested in also supporting the new RTOS SDK (https://github.com/espressif/esp_iot_rtos_sdk) as a switch in the Makefile or similar?

Thanks!

**Comment by borg42** [comment]
I just found this pull request: https://github.com/pfalcon/esp-open-sdk/pull/29
Should have looked for that before opening an issue ;-).

**Comment by pfalcon** [comment]
See also https://github.com/SuperHouse/esp-open-rtos
