### ISSUE TITLE
(Pre)Build fails with Extracting and Patching Toolcahin Components: "gzip: /opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/tarballs/mpc-1.0.2.tar.gz: not in gzip format" 

### ISSUE THREAD

**Issue by Top-Dog** [pfalcon/esp-open-sdk#74]
So when I try and run make (after a fresh pull) for either the standalone or non-standlone version of the toolchain the gathering of resource files fails.
  
[DEBUG]    ==> Executing: 'touch' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/.cloog-0.18.1.extracted' 
[DEBUG]    ==> Executing: 'rm' '-f' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/.cloog-0.18.1.extracting' 
[DEBUG]    Entering '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/cloog-0.18.1'
[EXTRA]    Patching 'cloog-0.18.1'
[DEBUG]    Looking for patches in '/opt/Espressif/esp-open-sdk-n/crosstool-NG/lib/ct-ng.1.20.0/patches/cloog/0.18.1'...
[DEBUG]    Looking for patches in ''...
[DEBUG]    Looking for patches in '/opt/Espressif/esp-open-sdk-n/crosstool-NG/local-patches/cloog/0.18.1'...
[DEBUG]    Looking for patches in ''...
[ALL  ]    Overiding config.guess and config.sub
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.guess' -> './autoconf/config.guess'
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.guess' -> './osl/autoconf/config.guess'
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.guess' -> './isl/config.guess'
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.sub' -> './autoconf/config.sub'
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.sub' -> './osl/autoconf/config.sub'
[ALL  ]    '/opt/Espressif/esp-open-sdk-n/crosstool-NG/scripts/config.sub' -> './isl/config.sub'
[DEBUG]    ==> Executing: 'touch' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/.cloog-0.18.1.patched' 
[DEBUG]    ==> Executing: 'rm' '-f' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/.cloog-0.18.1.patching' 
[DEBUG]    ==> Executing: 'mkdir' '-p' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/cloog-0.18.1/m4' 
[DEBUG]    ==> Executing: 'touch' '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src/.mpc-1.0.2.extracting' 
[DEBUG]    Entering '/opt/Espressif/esp-open-sdk-n/crosstool-NG/.build/src'
[EXTRA]    Extracting 'mpc-1.0.2'
[DEBUG]    ==> Executing: 'mkdir' '-p' 'mpc-1.0.2' 
[DEBUG]    ==> Executing: 'tar' '--strip-components=1' '-C' 'mpc-1.0.2' '-xv' '-f' '-' 
[FILE ]    tar: This does not look like a tar archive
[FILE ]    tar: Exiting with failure status due to previous errors
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: CT_Extract[scripts/functions@958]
[ERROR]  >>        called from: do_mpc_extract[scripts/build/companion_libs/140-mpc.sh@21]
[ERROR]  >>        called from: do_companion_libs_extract[scripts/build/companion_libs.sh@22]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@606]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 13:55.57)

**Comment by pfalcon** [comment]
Ok, so you had a problem with your downloads. Remove broken file and retry. If problem persists, report it to crosstool-NG.
