### ISSUE TITLE
Can't get IoT demo example to build..

### ISSUE THREAD

**Issue by DrObscure** [pfalcon/esp-open-sdk#78]
Trying to build the default IoT example in the sdk/examples tree.. should these be buildable as delivered, or did I miss reading a document, etc.. 

All I get from the make when running gen_misc.sh is the following after the input questions, which I choose the defaults:

*start...
gmake: Nothing to be done for 'FORCE'.*

The makefile seems rather sparse, and I am under the impression there is no parent makefile that should be called above it..

**Comment by DrObscure** [comment]
Ok.. rewrote the makefile to work locally...

**Comment by g-goessel** [comment]
Can you share your solution? 

Le 8 août 2015 8:38 AM, "Dr. Obscure" <notifications@github.com> a écrit :

Ok.. rewrote the makefile to work locally...

**Comment by DrObscure** [comment]
This message was originally HTML formatted.  View in a HTML capable client to see the original version.\r\n\r\nBe glad to once I resolve a linking issue I'm having..
I'll post it when completed..

---- Original Message ----

**Comment by l29ah** [comment]
Any luck?

**Comment by DrObscure** [comment]
Hi Sergey.. yes i did finally :)
I did have issues trying to load the firmware to the device, and haven't 
had time revisit it again - sigh..
I hope to get back into it again.. its on my schedule for next month.. :)

**Comment by rakeshsafir** [comment]
Hey DrObscure.
I'm troubled with the same issue of examples not compiling. The issue is same with every example in the sdk. Seems you solved the compilation part. Can you please share your solution.

**Comment by DrObscure** [comment]
This message was originally HTML formatted.  View in a HTML capable client to see the original version.\r\n\r\nHi Rakesh...
Its been a while since I did this, and will need to revisit my notes and such..
This next coming week I am traveling, so it will have to wait until I get back to my office and such..
FYI, I did this on a FreeBSD 10.1 system, so it may be different on another system
Talk at you after next week or so..
  --DrObscure



---- Original Message ----
