### ISSUE TITLE
Where is ets_memcpy defined?

### ISSUE THREAD

**Issue by DrObscure** [pfalcon/esp-open-sdk#80]
In building the IoT example in the sdk/ I fail to link the build due to missing defined functions in the libs --
I searched the symbol tables for all the libs built with the toolchain, but can't find a defined reference to ets_memcpy and several other ets_ functions...  

What lib am I missing? or failed to build... note: I built the toolchain as STANDALONE=n

/research/Esp8266/esp-open-sdk/esp_iot_sdk_v1.2.0/lib/libwpa.a(wpas_glue.o):(.irom0.text+0x48): undefined reference to `ets_memcpy'
/research/Esp8266/esp-open-sdk/esp_iot_sdk_v1.2.0/lib/libwpa.a(wpas_glue.o):(.irom0.text+0x57): undefined reference to `ets_memset'
/research/Esp8266/esp-open-sdk/esp_iot_sdk_v1.2.0/lib/libwpa.a(aes-wrap.o):(.irom0.text+0x1f): undefined reference to `ets_memset'
/research/Esp8266/esp-open-sdk/esp_iot_sdk_v1.2.0/lib/libwpa.a(aes-wrap.o): In function `aes_wrap':
(.irom0.text+0x30): undefined reference to `ets_memcpy'

**Comment by pfalcon** [comment]
This isn't good place to get support for vendor SDK, try to contact vendor directly. But let me guess: if you grep vendor SDK in its entirety, you will quickly find where something is defined.
