### ISSUE TITLE
Unable to build on Ubunutu 14.04

### ISSUE THREAD

**Issue by rubberbird** [pfalcon/esp-open-sdk#89]
esp-open-sdk/crosstool-NG/.build/tarballs/mpc-1.0.2.tar.gz: not in gzip format

**Comment by pfalcon** [comment]
Random download error on your side.

**Comment by rubberbird** [comment]
Thats what I thought, but after downloading the file seperately for 4 different sources and testing a tar xvf manually to make sure it was the right format, still the same error. Do you have a good source of this file that I can test?

**Comment by rubberbird** [comment]
Pulling from the official site and it works. Sorry about that. Thanks for the code :+1:

**Comment by Top-Dog** [comment]
What were the steps you used to get around this? I can't seem to get around this problem.

**Comment by SBlincov** [comment]
@Top-Dog Try to do it:
1) Delete crosstool-NG from root of esp-open-sdk
2) Make tmp directory
`mkdir tmp`
`cd tmp`
3) Clone crosstool-NG repository 
`git clone https://github.com/crosstool-ng/crosstool-ng`  
4) Replace downloaded crosstool to root of esp-open-sdk
5) Change name "crosstool-ng" on "crosstool-NG"
