### ISSUE TITLE
Timeouts for download, isl-0.12.2 not where it's looked for

### ISSUE THREAD

**Issue by UserXYZ** [pfalcon/esp-open-sdk#99]
isl-0.12.2 that needs to be downloaded is not at the given urls, and so configure/download/build script fails numerous times to download it.
ftp.linux.student.kuleuven.be is offline, only working copy is http://mirrors.kernel.org/sources.redhat.com/gcc/infrastructure/isl-0.12.2.tar.bz2

Can you fix the sources to ensure availability of all files and avoid timeouts?

Thanks.

**Comment by pfalcon** [comment]
See #100.
